{% set name = "microsoft-kiota-serialization-form" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_serialization_form-{{ version }}.tar.gz
  sha256: ee6620b2f3b8b5294b204de3702352c838541de653d825ba1dee55ca2d27eda5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8,<4.0
    - microsoft-kiota-abstractions
    - pendulum >=3.0.0b1

test:
  imports:
    - kiota_serialization_form
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/serialization/form
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
